config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :test_email_modals

   root 'test_email_modals#index'

end

app/models/email_modal.rb
class EmailModal < ActiveRecord::Base
end

app/models/test_email_modal.rb
class TestEmailModal < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?
   before_action :authenticate_user!, :except => :index


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password])
  end
end

app/controllers/test_email_modals_controller.rb
class TestEmailModalsController < ApplicationController
  before_action :set_test_email_modal, only: [:show, :edit, :update, :destroy]

  # GET /test_email_modals
  # GET /test_email_modals.json
  def index
    @test_email_modals = TestEmailModal.all
  end

  # GET /test_email_modals/1
  # GET /test_email_modals/1.json
  def show
  end

  # GET /test_email_modals/new
  def new
    @test_email_modal = TestEmailModal.new
  end

  # GET /test_email_modals/1/edit
  def edit
  end

  # POST /test_email_modals
  # POST /test_email_modals.json
  def create
    @test_email_modal = TestEmailModal.new(test_email_modal_params)

    respond_to do |format|
      if @test_email_modal.save
        format.html { redirect_to @test_email_modal, notice: 'Test email modal was successfully created.' }
        format.json { render :show, status: :created, location: @test_email_modal }
      else
        format.html { render :new }
        format.json { render json: @test_email_modal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_email_modals/1
  # PATCH/PUT /test_email_modals/1.json
  def update
    respond_to do |format|
      if @test_email_modal.update(test_email_modal_params)
        format.html { redirect_to @test_email_modal, notice: 'Test email modal was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_email_modal }
      else
        format.html { render :edit }
        format.json { render json: @test_email_modal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_email_modals/1
  # DELETE /test_email_modals/1.json
  def destroy
    @test_email_modal.destroy
    respond_to do |format|
      format.html { redirect_to test_email_modals_url, notice: 'Test email modal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_email_modal
      @test_email_modal = TestEmailModal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_email_modal_params
      params.require(:test_email_modal).permit(:title, :content, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_email_modals_helper.rb
module TestEmailModalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmailModalTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.name %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/test_email_modals/_form.html.erb
<%= form_for(@test_email_modal) do |f| %>
  <% if @test_email_modal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_email_modal.errors.count, "error") %> prohibited this test_email_modal from being saved:</h2>

      <ul>
      <% @test_email_modal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_email_modals/edit.html.erb
<h1>Editing Test Email Modal</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_email_modal %> |
<%= link_to 'Back', test_email_modals_path %>

app/views/test_email_modals/index.html.erb
<h1>Listing Test Email Modals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_email_modals.each do |test_email_modal| %>
      <tr>
        <td><%= test_email_modal.title %></td>
        <td><%= test_email_modal.content %></td>
        <td><%= test_email_modal.slug %></td>
        <td><%= link_to 'Show', test_email_modal %></td>
        <td><%= link_to 'Edit', edit_test_email_modal_path(test_email_modal) %></td>
        <td><%= link_to 'Destroy', test_email_modal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test email modal', new_test_email_modal_path %>

app/views/test_email_modals/new.html.erb
<h1>New Test Email Modal</h1>

<%= render 'form' %>

<%= link_to 'Back', test_email_modals_path %>

app/views/test_email_modals/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @test_email_modal.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @test_email_modal.content %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @test_email_modal.slug %>
</p>

<%= link_to 'Edit', edit_test_email_modal_path(@test_email_modal) %> |
<%= link_to 'Back', test_email_modals_path %> | 
<a data-toggle="modal" href="#email-modal-form-content" class=" email_share_button">Share</a> 

<div class="modal fade" id="email-modal-form-content" role="dialog">
    <div class="modal-dialog modal-sm"> 
    
      <!-- Modal content-->
      <div class="modal-content ">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="Taxworld-Subhead" style="color: #3262a0">Share this page</h3>
        </div>

        <div class="modal-body ">
          <form action="<?php the_permalink(); ?>" method="post" role="form" id="shareForm">
      <div class="email-modal-form-group <?php echo $required;?>">
        <label for="name"><font color="#3262a0">Your Name:<sup>*</sup></font> <small><span class="text-danger"><?php echo $field;?></span></small></label>
        <input type="text" class="form-control name" name="contact_name" id="name" placeholder="Name" value='<%= current_user.name %>' readonly required>
      </div>

      <div class="email-modal-form-group <?php echo $required;?>">
        <label for="email"><font color="#3262a0">Email:<sup>*</sup></font> <small><span class="text-danger"><?php echo $field;?></small></label>
        <input type="email" class="form-control email" name="contact_email" id="email" placeholder="Email" required>  
      </div>

      <div class="email-modal-form-group <?php echo $required;?>">
        <label for="message"><font color="#3262a0">Message:<sup>*</sup></font> <small><span class="text-danger"><?php echo $field;?></small></label>
        <textarea class="form-control message" name="contact_message" rows="5" id="message" placeholder="Message" required readonly></textarea>
      </div>
    </form>
        </div>

        <div class="modal-footer ">
          <button class="btn btn-primary share_page" type="submit" form="shareForm" value="Submit" name="share_page_button" >Submit</button>
        </div>
      </div>
      
    </div>
  </div>

<script type="text/javascript">
jQuery(document).ready(function($) {
  $('div').find('a:contains("Contact")').addClass("taxworld-active");
  $(document).ready(function () {
    $(".email_share_button").click(function(){
      var link = $(location).attr('href');
      $("#message").val(link);
    });          
  });
});
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>